PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS TransactionLines;
DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS Accounts;

PRAGMA foreign_keys = ON;

-- Create tables with autoincrement Ids
CREATE TABLE IF NOT EXISTS Accounts (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL CHECK(length(Name) <= 200),
    Description TEXT NOT NULL,
    FinancialStatement TEXT NOT NULL,
    CreatedAt TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    ParentId INTEGER,
    FOREIGN KEY (ParentId) REFERENCES Accounts(Id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Transactions (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    AccountId INTEGER NOT NULL,
    Description TEXT,
    Date TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    FOREIGN KEY (AccountId) REFERENCES Accounts(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TransactionLines (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    TransactionId INTEGER NOT NULL,
    AccountId INTEGER NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Description TEXT,
    FOREIGN KEY (TransactionId) REFERENCES Transactions(Id) ON DELETE CASCADE,
    FOREIGN KEY (AccountId) REFERENCES Accounts(Id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS IX_Accounts_ParentId ON Accounts(ParentId);
CREATE INDEX IF NOT EXISTS IX_Transactions_AccountId ON Transactions(AccountId);
CREATE INDEX IF NOT EXISTS IX_TransactionLines_TransactionId ON TransactionLines(TransactionId);
CREATE INDEX IF NOT EXISTS IX_TransactionLines_AccountId ON TransactionLines(AccountId);

--------------------------------------------------------------------------------
-- Seed top-level accounts (Id autogenerated)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Auto & Transport',        'Vehicle and transportation costs',         'EXPENSE', NULL),
('Travel & Life Style',     'Travel, leisure and lifestyle expenses',  'EXPENSE', NULL),
('Shopping',                'Clothing, furniture, electronics, etc.',  'EXPENSE', NULL),
('Food & Dining',           'Restaurants, groceries, coffee',          'EXPENSE', NULL),
('Utilities',               'Electricity, gas, phone, water, etc.',    'EXPENSE', NULL),
('Housing',                 'Rent, mortgage, home maintenance',        'EXPENSE', NULL),
('Income',                  'All income sources',                      'REVENUE', NULL),
('Savings',                 'Bank savings and reserve accounts',       'ASSET', NULL),
('Cash & Bank',             'Cash, checking and bank accounts',        'ASSET', NULL),
('Liabilities',             'Credit cards, loans and other liabilities','LIABILITY', NULL),
('Equity',                  'Owner equity / net worth buckets',        'EQUITY', NULL),
('Other Expenses',          'Miscellaneous expense buckets',           'EXPENSE', NULL);

--------------------------------------------------------------------------------
-- Auto & Transport subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Maintenance',        'Car maintenance and repairs',           'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1)),
('Gas',                'Fuel purchases',                        'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1)),
('Taxi & Ride Shares', 'Uber, Lyft, taxis',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1)),
('Public Transit',     'Subway, buses, transit tickets',        'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1)),
('Parking & Tolls',    'Parking fees and tolls',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1));

--------------------------------------------------------------------------------
-- Travel & Life Style subaccounts (includes travel-specific martial arts/gym)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Travel & Vacations',       'Trips, flights, hotels',                 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1)),
('Pets',                     'Pet food, vet, supplies',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1)),
('Entertainment & Recreation','Movies, events, hobbies',               'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1)),
('Martial Arts (Travel)',    'Martial arts classes/training while on vacation', 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1)),
('Gym (Travel)',             'Gym passes or classes while on vacation', 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1)),
('Restaurants (Travel)',     'Dining while traveling',                 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1));

--------------------------------------------------------------------------------
-- Shopping subaccounts (including electronics/appliances)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Clothing',                 'Clothes and accessories',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Shopping' LIMIT 1)),
('Furniture & Housewares',   'Furniture, home goods',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Shopping' LIMIT 1)),
('Other Shopping',           'General shopping misc',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Shopping' LIMIT 1)),
('Electronics & Appliances','Fridges, microwaves, TVs, computers',     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Shopping' LIMIT 1));

--------------------------------------------------------------------------------
-- Food & Dining subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Restaurants',              'Eating out',                             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Food & Dining' LIMIT 1)),
('Groceries',                'Supermarket and grocery stores',         'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Food & Dining' LIMIT 1)),
('Coffee Shops',             'Cafes and coffee purchases',             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Food & Dining' LIMIT 1));

--------------------------------------------------------------------------------
-- Utilities subaccounts (electricity, gas, phone, etc.)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Electricity',              'Electric bills',                         'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1)),
('Gas (Utility)',            'Home heating / gas utility',             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1)),
('Water',                    'Water bills',                            'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1)),
('Phone & Internet',         'Mobile phone and internet services',     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1)),
('Trash & Recycling',        'Waste collection fees',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1));

--------------------------------------------------------------------------------
-- Housing subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Rent',                     'Monthly rent payments',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1)),
('Mortgage',                 'Mortgage payments (interest/principal)', 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1)),
('Home Insurance',           'Home insurance premiums',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1)),
('Property Taxes',           'Local property taxes',                   'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1)),
('Home Maintenance',         'Repairs and upkeep',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1));

--------------------------------------------------------------------------------
-- Income subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Salary',                   'Employment wages and salary',            'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1)),
('Business Income',          'Freelance or business revenue',          'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1)),
('Investment Income',        'Dividends, capital gains',               'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1)),
('Interest Income',          'Bank interest',                          'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1)),
('Refunds & Rebates',        'Refunds, rebates, returned purchases',   'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1));

--------------------------------------------------------------------------------
-- Savings subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Emergency Fund',           'Short-term emergency savings'                      , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1)),
('Business Fund',            'Fund to create or invest on a business'            , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1)),
('Motorcycle Fund',          'Fund to buy a new one or to spent in a current one', 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1)),
('Retirement',               'Retirement accounts (IRA, 401k)'                   , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1)),
('Short Term Savings',       'Planned short-term goals'                          , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1)),
('Long Term Savings',        'Long-term goals and investments'                   , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1));

--------------------------------------------------------------------------------
-- Cash & Bank subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Cash on Hand',             'Physical cash',                          'ASSET', (SELECT Id FROM Accounts WHERE Name='Cash & Bank' LIMIT 1)),
('Checking Account',         'Primary checking account',               'ASSET', (SELECT Id FROM Accounts WHERE Name='Cash & Bank' LIMIT 1)),
('Bank Savings Account',     'Bank savings account',                   'ASSET', (SELECT Id FROM Accounts WHERE Name='Cash & Bank' LIMIT 1));

--------------------------------------------------------------------------------
-- Liabilities subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Credit Card',              'Credit card balances',                   'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1)),
('Auto Loan',                'Auto loan principal',                    'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1)),
('Student Loan',             'Student loan balances',                  'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1)),
('Mortgage Loan',            'Mortgage principal',                     'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1)),
('Other Liabilities',        'Other owed balances',                    'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1));

--------------------------------------------------------------------------------
-- Other Expenses subaccounts (includes local martial arts/gym variants)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Subscriptions',            'Streaming, software, memberships',       'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1)),
('Fees & Charges',           'Service fees, late fees',                 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1)),
('Bank Fees',                'Account and transaction fees',           'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1)),
('Miscellaneous',            'Unclassified small expenses',            'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1)),
('Martial Arts (Local)',     'Martial arts classes and training (local)', 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1)),
('Gym (Local)',              'Gym memberships or classes (local)',     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1));

--------------------------------------------------------------------------------
-- Electronics & Appliances detailed items under Shopping
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Fridge',                   'Refrigerator purchase',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1)),
('Microwave',                'Microwave purchase',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1)),
('TV',                       'Television purchase',                    'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1)),
('Computer',                 'Laptop / desktop purchase',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1)),
('Other Electronics',        'Other electronic devices',               'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1));