PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS TransactionLines;
DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS Accounts;

PRAGMA foreign_keys = ON;

-- Create tables with autoincrement Ids
CREATE TABLE IF NOT EXISTS Accounts (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL CHECK(length(Name) <= 200),
    Description TEXT NOT NULL,
    FinancialStatement TEXT NOT NULL,
    CreatedAt TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    ParentId INTEGER,
    FOREIGN KEY (ParentId) REFERENCES Accounts(Id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Transactions (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Description TEXT,
    Date TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE IF NOT EXISTS TransactionLines (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    TransactionId INTEGER NOT NULL,
    AccountId INTEGER NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Description TEXT,
    FOREIGN KEY (TransactionId) REFERENCES Transactions(Id) ON DELETE CASCADE,
    FOREIGN KEY (AccountId) REFERENCES Accounts(Id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS IX_Accounts_ParentId ON Accounts(ParentId);
CREATE INDEX IF NOT EXISTS IX_TransactionLines_TransactionId ON TransactionLines(TransactionId);
CREATE INDEX IF NOT EXISTS IX_TransactionLines_AccountId ON TransactionLines(AccountId);

--------------------------------------------------------------------------------
-- Seed top-level accounts (Id autogenerated)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Auto & Transport',        'Vehicle and transportation costs',         'EXPENSE', NULL),
('Travel & Life Style',     'Travel, leisure and lifestyle expenses',  'EXPENSE', NULL),
('Shopping',                'Clothing, furniture, electronics, etc.',  'EXPENSE', NULL),
('Food & Dining',           'Restaurants, groceries, coffee',          'EXPENSE', NULL),
('Utilities',               'Electricity, gas, phone, water, etc.',    'EXPENSE', NULL),
('Housing',                 'Rent, mortgage, home maintenance',        'EXPENSE', NULL),
('Income',                  'All income sources',                      'REVENUE', NULL),
('Savings',                 'Bank savings and reserve accounts',       'ASSET', NULL),
('Cash & Bank',             'Cash, checking and bank accounts',        'ASSET', NULL),
('Liabilities',             'Credit cards, loans and other liabilities','LIABILITY', NULL),
('Equity',                  'Owner equity / net worth buckets',        'EQUITY', NULL),
('Personal Care',           'Health, hygiene, and personal grooming',   'EXPENSE', NULL),
('Health & Medicine',        'Healthcare, medications, and wellness',   'EXPENSE', NULL),
('Alcohol & Tobacco',        'Alcoholic beverages and tobacco products', 'EXPENSE', NULL),
('Tools & Equipment',        'Tools for home repairs and maintenance',   'EXPENSE', NULL),
('Cleaning Supplies',        'Household cleaning products',               'EXPENSE', NULL),
('Office & Stationery',      'Home office and writing supplies',         'EXPENSE', NULL),
('Gifts & Donations',        'Gift purchases and charitable contributions', 'EXPENSE', NULL),
('Other Expenses',          'Miscellaneous expense buckets',           'EXPENSE', NULL);

--------------------------------------------------------------------------------
-- Auto & Transport subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Maintenance',        'Car maintenance and repairs',           'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1)),
('Gas',                'Fuel purchases',                        'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1)),
('Taxi & Ride Shares', 'Uber, Lyft, taxis',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1)),
('Public Transit',     'Subway, buses, transit tickets',        'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1)),
('Parking & Tolls',    'Parking fees and tolls',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Auto & Transport' LIMIT 1));

--------------------------------------------------------------------------------
-- Travel & Life Style subaccounts (includes travel-specific martial arts/gym)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Travel & Vacations',       'Trips, flights, hotels',                 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1)),
('Pets',                     'Pet food, vet, supplies',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1)),
('Entertainment & Recreation','Movies, events, hobbies',               'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1)),
('Martial Arts (Travel)',    'Martial arts classes/training while on vacation', 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1)),
('Gym (Travel)',             'Gym passes or classes while on vacation', 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1)),
('Restaurants (Travel)',     'Dining while traveling',                 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Travel & Life Style' LIMIT 1));

--------------------------------------------------------------------------------
-- Shopping subaccounts (including electronics/appliances)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Clothing',                 'Clothes and accessories',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Shopping' LIMIT 1)),
('Furniture & Housewares',   'Furniture, home goods',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Shopping' LIMIT 1)),
('Other Shopping',           'General shopping misc',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Shopping' LIMIT 1)),
('Electronics & Appliances','Fridges, microwaves, TVs, computers',     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Shopping' LIMIT 1));

--------------------------------------------------------------------------------
-- Food & Dining subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Restaurants',              'Eating out',                             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Food & Dining' LIMIT 1)),
('Groceries',                'Supermarket and grocery stores',         'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Food & Dining' LIMIT 1)),
('Coffee Shops',             'Cafes and coffee purchases',             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Food & Dining' LIMIT 1));

--------------------------------------------------------------------------------
-- Utilities subaccounts (electricity, gas, phone, etc.)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Electricity',              'Electric bills',                         'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1)),
('Gas (Utility)',            'Home heating / gas utility',             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1)),
('Water',                    'Water bills',                            'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1)),
('Phone & Internet',         'Mobile phone and internet services',     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1)),
('Trash & Recycling',        'Waste collection fees',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Utilities' LIMIT 1));

--------------------------------------------------------------------------------
-- Housing subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Rent',                     'Monthly rent payments',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1)),
('Mortgage',                 'Mortgage payments (interest/principal)', 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1)),
('Home Insurance',           'Home insurance premiums',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1)),
('Property Taxes',           'Local property taxes',                   'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1)),
('Home Maintenance',         'Repairs and upkeep',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Housing' LIMIT 1));

--------------------------------------------------------------------------------
-- Income subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Salary',                   'Employment wages and salary',            'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1)),
('Business Income',          'Freelance or business revenue',          'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1)),
('Investment Income',        'Dividends, capital gains',               'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1)),
('Interest Income',          'Bank interest',                          'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1)),
('Refunds & Rebates',        'Refunds, rebates, returned purchases',   'REVENUE', (SELECT Id FROM Accounts WHERE Name='Income' LIMIT 1));

--------------------------------------------------------------------------------
-- Savings subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Emergency Fund',           'Short-term emergency savings'                      , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1)),
('Business Fund',            'Fund to create or invest on a business'            , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1)),
('Motorcycle Fund',          'Fund to buy a new one or to spent in a current one', 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1)),
('Retirement',               'Retirement accounts (IRA, 401k)'                   , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1)),
('Short Term Savings',       'Planned short-term goals'                          , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1)),
('Long Term Savings',        'Long-term goals and investments'                   , 'ASSET', (SELECT Id FROM Accounts WHERE Name='Savings' LIMIT 1));

--------------------------------------------------------------------------------
-- Cash & Bank subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Cash on Hand',             'Physical cash',                          'ASSET', (SELECT Id FROM Accounts WHERE Name='Cash & Bank' LIMIT 1)),
('Checking Account',         'Primary checking account',               'ASSET', (SELECT Id FROM Accounts WHERE Name='Cash & Bank' LIMIT 1)),
('Bank Savings Account',     'Bank savings account',                   'ASSET', (SELECT Id FROM Accounts WHERE Name='Cash & Bank' LIMIT 1));

--------------------------------------------------------------------------------
-- Liabilities subaccounts
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Credit Card',              'Credit card balances',                   'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1)),
('Auto Loan',                'Auto loan principal',                    'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1)),
('Student Loan',             'Student loan balances',                  'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1)),
('Mortgage Loan',            'Mortgage principal',                     'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1)),
('Other Liabilities',        'Other owed balances',                    'LIABILITY', (SELECT Id FROM Accounts WHERE Name='Liabilities' LIMIT 1));

--------------------------------------------------------------------------------
-- Other Expenses subaccounts (includes local martial arts/gym variants)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Subscriptions',            'Streaming, software, memberships',       'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1)),
('Fees & Charges',           'Service fees, late fees',                 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1)),
('Bank Fees',                'Account and transaction fees',           'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1)),
('Miscellaneous',            'Unclassified small expenses',            'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1)),
('Martial Arts (Local)',     'Martial arts classes and training (local)', 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1)),
('Gym (Local)',              'Gym memberships or classes (local)',     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Other Expenses' LIMIT 1));

--------------------------------------------------------------------------------
-- Electronics & Appliances detailed items under Shopping
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Fridge',                   'Refrigerator purchase',                  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1)),
('Microwave',                'Microwave purchase',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1)),
('TV',                       'Television purchase',                    'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1)),
('Computer',                 'Laptop / desktop purchase',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1)),
('Other Electronics',        'Other electronic devices',               'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Electronics & Appliances' LIMIT 1));

--------------------------------------------------------------------------------
-- Equity subaccounts (owner's equity / net worth buckets)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Owner''s Capital',         'Initial and additional owner investments',     'EQUITY', (SELECT Id FROM Accounts WHERE Name='Equity' LIMIT 1)),
('Retained Earnings',        'Accumulated profits not distributed',           'EQUITY', (SELECT Id FROM Accounts WHERE Name='Equity' LIMIT 1)),
('Current Year Earnings',    'Net income for the current fiscal year',        'EQUITY', (SELECT Id FROM Accounts WHERE Name='Equity' LIMIT 1)),
('Dividends/Drawings',       'Owner withdrawals or dividends paid',           'EQUITY', (SELECT Id FROM Accounts WHERE Name='Equity' LIMIT 1)),
('Paid-in Capital',          'Additional paid-in capital beyond par value',   'EQUITY', (SELECT Id FROM Accounts WHERE Name='Equity' LIMIT 1)),
('Treasury Stock',           'Company''s own shares repurchased',             'EQUITY', (SELECT Id FROM Accounts WHERE Name='Equity' LIMIT 1)),
('Other Comprehensive Income', 'Unrealized gains/losses not in net income',   'EQUITY', (SELECT Id FROM Accounts WHERE Name='Equity' LIMIT 1));

--------------------------------------------------------------------------------
-- Personal Care & Hygiene (new top-level expense category)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Shampoo & Conditioner',    'Hair care products',                          'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1)),
('Soap & Body Wash',         'Bathing and cleansing products',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1)),
('Deodorant',                'Antiperspirants and deodorants',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1)),
('Toothpaste & Oral Care',   'Dental hygiene products',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1)),
('Shaving & Grooming',       'Razors, shaving cream, trimmers',             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1)),
('Skincare',                 'Moisturizers, sunscreen, facial products',     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1)),
('Makeup & Cosmetics',       'Cosmetic products',                           'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1)),
('Haircuts & Salon',         'Professional haircuts and salon services',    'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Personal Care' LIMIT 1));

--------------------------------------------------------------------------------
-- Health & Medicine (new top-level expense category)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Prescriptions',            'Prescription medications',                    'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1)),
('Over-the-Counter Drugs',   'OTC medicines (pain relievers, cold meds)',   'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1)),
('Vitamins & Supplements',   'Dietary supplements and vitamins',            'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1)),
('Doctor Visits',            'Medical consultations and checkups',          'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1)),
('Dental Care',              'Dentist visits, cleanings, procedures',       'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1)),
('Vision Care',              'Eye exams, glasses, contact lenses',          'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1)),
('Health Insurance',         'Health insurance premiums',                   'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1)),
('Therapy & Mental Health',  'Counseling, therapy sessions',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1)),
('First Aid Supplies',       'Bandages, antiseptics, first aid kits',       'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Health & Medicine' LIMIT 1));

--------------------------------------------------------------------------------
-- Alcohol & Tobacco (new top-level expense category)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Beer',                     'Beer purchases',                              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Alcohol & Tobacco' LIMIT 1)),
('Wine',                     'Wine purchases',                              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Alcohol & Tobacco' LIMIT 1)),
('Spirits & Liquor',         'Hard liquor and spirits',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Alcohol & Tobacco' LIMIT 1)),
('Cigarettes',               'Cigarette purchases',                         'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Alcohol & Tobacco' LIMIT 1)),
('Vaping Products',          'E-cigarettes, vape juice, accessories',       'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Alcohol & Tobacco' LIMIT 1)),
('Cigars',                   'Cigar purchases',                             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Alcohol & Tobacco' LIMIT 1));

--------------------------------------------------------------------------------
-- Home Maintenance & Tools (expanding under Housing or as new top-level)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Hand Tools',               'Wrenches, screwdrivers, hammers',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Tools & Equipment' LIMIT 1)),
('Power Tools',              'Drills, saws, sanders',                        'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Tools & Equipment' LIMIT 1)),
('Mechanic Tools',           'Car repair tools, jacks, stands',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Tools & Equipment' LIMIT 1)),
('Gardening Tools',          'Shovels, rakes, trimmers',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Tools & Equipment' LIMIT 1)),
('Tool Storage',             'Toolboxes, pegboards, organizers',             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Tools & Equipment' LIMIT 1)),
('Safety Equipment',         'Gloves, goggles, masks, safety gear',          'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Tools & Equipment' LIMIT 1));

--------------------------------------------------------------------------------
-- Cleaning Supplies (new top-level expense category)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('All-Purpose Cleaner',      'Multi-surface cleaning solutions',            'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Cleaning Supplies' LIMIT 1)),
('Laundry Detergent',        'Laundry soap, fabric softener, stain removers', 'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Cleaning Supplies' LIMIT 1)),
('Dish Soap',                'Dishwashing liquid and dishwasher detergent',  'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Cleaning Supplies' LIMIT 1)),
('Bathroom Cleaners',        'Toilet, tub, and tile cleaners',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Cleaning Supplies' LIMIT 1)),
('Floor Cleaners',           'Mop solutions, floor wax',                    'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Cleaning Supplies' LIMIT 1)),
('Paper Products',           'Paper towels, tissues, toilet paper',         'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Cleaning Supplies' LIMIT 1)),
('Trash Bags',               'Garbage bags and liners',                     'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Cleaning Supplies' LIMIT 1));

--------------------------------------------------------------------------------
-- Office & Stationery (new top-level expense category)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Paper & Envelopes',        'Printer paper, envelopes, notepads',          'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Office & Stationery' LIMIT 1)),
('Pens & Pencils',           'Writing instruments and refills',             'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Office & Stationery' LIMIT 1)),
('Printer Ink & Toner',      'Printer cartridges',                          'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Office & Stationery' LIMIT 1)),
('Office Furniture',         'Desks, chairs, filing cabinets',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Office & Stationery' LIMIT 1)),
('Postage & Shipping',       'Stamps, shipping supplies',                   'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Office & Stationery' LIMIT 1)),
('Calendars & Planners',     'Organizational tools',                        'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Office & Stationery' LIMIT 1));

--------------------------------------------------------------------------------
-- Gifts & Donations (new top-level expense category)
--------------------------------------------------------------------------------
INSERT INTO Accounts (Name, Description, FinancialStatement, ParentId) VALUES
('Birthday Gifts',           'Birthday presents for others',                'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Gifts & Donations' LIMIT 1)),
('Holiday Gifts',            'Christmas, holiday gift giving',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Gifts & Donations' LIMIT 1)),
('Charitable Donations',     'Donations to charities and causes',           'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Gifts & Donations' LIMIT 1)),
('Wedding Gifts',            'Wedding presents',                            'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Gifts & Donations' LIMIT 1)),
('Baby Gifts',               'Baby shower and new baby gifts',              'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Gifts & Donations' LIMIT 1)),
('Gift Wrapping',            'Wrapping paper, bags, ribbons',               'EXPENSE', (SELECT Id FROM Accounts WHERE Name='Gifts & Donations' LIMIT 1));
